# Generated by Django 5.1.4 on 2026-04-29 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('b2bmanagement', '0053_branch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SalesProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('commission_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vat_percent', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='SalesRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('hierarchy_level', models.PositiveIntegerField(help_text='\n            1=National Head\n            2=Regional Manager\n            3=Zonal Manager\n            4=Area Manager\n            5=Branch Manager\n            6=Sales Officer\n            7=Agent\n            ')),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('model_name', models.CharField(max_length=100)),
                ('record_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommissionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_achievement', models.DecimalField(decimal_places=2, max_digits=5)),
                ('commission_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('override_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='b2bmanagement.designation')),
            ],
        ),
        migrations.CreateModel(
            name='SalesEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(max_length=30, unique=True)),
                ('phone', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], default='ACTIVE', max_length=20)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='b2bmanagement.branch')),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='salesman_management.channel')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='b2bmanagement.department')),
                ('designation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='b2bmanagement.designation')),
                ('line_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='line_reports', to='salesman_management.salesemployee')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='salesman_management.salesemployee')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='salesman_management.salesrole')),
            ],
        ),
        migrations.CreateModel(
            name='PolicySale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_no', models.CharField(max_length=50, unique=True)),
                ('premium', models.DecimalField(decimal_places=2, max_digits=15)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('issue_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='salesman_management.salesemployee')),
                ('sales_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_policies', to='salesman_management.salesemployee')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='salesman_management.salesproduct')),
            ],
        ),
        migrations.CreateModel(
            name='OverrideCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('override_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesman_management.policysale')),
                ('upline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesman_management.salesemployee')),
            ],
        ),
        migrations.CreateModel(
            name='CommissionPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payout_date', models.DateField()),
                ('paid', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesman_management.salesemployee')),
            ],
        ),
        migrations.CreateModel(
            name='CommissionLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_commission', models.DecimalField(decimal_places=2, max_digits=15)),
                ('vat_deduction', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tax_deduction', models.DecimalField(decimal_places=2, max_digits=15)),
                ('net_commission', models.DecimalField(decimal_places=2, max_digits=15)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesman_management.policysale')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesman_management.salesemployee')),
            ],
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('status', models.CharField(max_length=30)),
                ('remarks', models.TextField(blank=True)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesman_management.policysale')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesman_management.salesemployee')),
            ],
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('target', models.DecimalField(decimal_places=2, max_digits=15)),
                ('achieved', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesman_management.salesemployee')),
            ],
        ),
        migrations.CreateModel(
            name='SalesGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesman_management.salesemployee')),
                ('parent_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='salesman_management.salesgroup')),
            ],
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesman_management.salesemployee')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesman_management.salesgroup')),
            ],
        ),
        migrations.CreateModel(
            name='SalesTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(blank=True, choices=[('designation', 'Designation'), ('group', 'Group'), ('individual', 'Individual')], max_length=20, null=True)),
                ('target_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targets_given', to='salesman_management.salesemployee')),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='b2bmanagement.designation')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='salesman_management.salesemployee')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='salesman_management.salesgroup')),
            ],
        ),
        migrations.CreateModel(
            name='VATLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vat_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tax_period', models.CharField(max_length=20)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesman_management.policysale')),
            ],
        ),
    ]
