# Generated by Django 5.1.4 on 2026-04-29 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2bmanagement', '0054_organizationsalesperson'),
        ('salesman_management', '0002_salesemployee_organization_sales_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesemployee',
            name='organization_sales_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_organizations', to='b2bmanagement.organizationpolicy'),
        ),
    ]
