# Generated by Django 5.1.4 on 2026-04-29 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesman_management', '0003_alter_salesemployee_organization_sales_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesemployee',
            name='organization_sales_person',
        ),
    ]
