# Generated by Django 5.1.4 on 2026-04-29 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesman_management', '0004_remove_salesemployee_organization_sales_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesemployee',
            name='employee_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
