# Generated by Django 5.1.4 on 2026-04-29 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesman_management', '0005_salesemployee_employee_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesemployee',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesemployee',
            name='father_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='salesemployee',
            name='mother_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
