# Generated by Django 5.1.4 on 2026-04-29 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesman_management', '0006_salesemployee_dob_salesemployee_father_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesemployee',
            name='status',
            field=models.IntegerField(choices=[(1, 'ACTIVE'), (2, 'INACTIVE')], default=1),
        ),
    ]
