# Generated by Django 5.1.4 on 2026-05-01 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesman_management', '0007_alter_salesemployee_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overridecommission',
            name='policy',
        ),
        migrations.RemoveField(
            model_name='commissionledger',
            name='policy',
        ),
        migrations.RemoveField(
            model_name='approval',
            name='sale',
        ),
        migrations.RemoveField(
            model_name='vatledger',
            name='policy',
        ),
        migrations.CreateModel(
            name='PremiumCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premimum_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('due_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('commision_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('collected_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('collection_date', models.DateField()),
                ('status', models.CharField(choices=[('partial', 'Partial'), ('full', 'Full')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collected_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesman_management.salesemployee')),
            ],
        ),
        migrations.DeleteModel(
            name='PolicySale',
        ),
    ]
