# Generated by Django 5.1.4 on 2026-05-02 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2bmanagement', '0055_organization_sales_employee_and_more'),
        ('salesman_management', '0008_remove_overridecommission_policy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='premiumcollection',
            name='commision_amount',
        ),
        migrations.RemoveField(
            model_name='premiumcollection',
            name='due_amount',
        ),
        migrations.RemoveField(
            model_name='premiumcollection',
            name='premimum_amount',
        ),
        migrations.AddField(
            model_name='premiumcollection',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='b2bmanagement.organization'),
        ),
        migrations.AlterField(
            model_name='premiumcollection',
            name='collected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='salesman_management.salesemployee'),
        ),
    ]
