# Generated by Django 5.1.4 on 2026-05-02 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2bmanagement', '0056_alter_bank_account_type_and_more'),
        ('salesman_management', '0009_remove_premiumcollection_commision_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumcollection',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collections', to='b2bmanagement.bank'),
        ),
        migrations.AddField(
            model_name='premiumcollection',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='premiumcollection',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='premiumcollection',
            name='bank_image',
            field=models.ImageField(blank=True, null=True, upload_to='bank_slips/'),
        ),
        migrations.AddField(
            model_name='premiumcollection',
            name='bank_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='premiumcollection',
            name='cash_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='premiumcollection',
            name='cash_received_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='premiumcollection',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='premiumcollection',
            name='commission_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='premiumcollection',
            name='due_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='premiumcollection',
            name='mfs_account_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='premiumcollection',
            name='mfs_provider_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='premiumcollection',
            name='mfs_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='premiumcollection',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('bank', 'Bank'), ('cash', 'Cash'), ('mfs', 'MFS')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='premiumcollection',
            name='premium_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='premiumcollection',
            name='collected_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='premiumcollection',
            name='collected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collections', to='salesman_management.salesemployee'),
        ),
    ]
