# Generated by Django 5.1.4 on 2026-05-02 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesman_management', '0010_premiumcollection_bank_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='premiumcollection',
            old_name='bank_account_number',
            new_name='account_number',
        ),
        migrations.RenameField(
            model_name='premiumcollection',
            old_name='bank_transaction_id',
            new_name='transaction_id',
        ),
        migrations.RemoveField(
            model_name='premiumcollection',
            name='mfs_account_number',
        ),
        migrations.RemoveField(
            model_name='premiumcollection',
            name='mfs_transaction_id',
        ),
    ]
