# Generated by Django 5.1.4 on 2026-05-02 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesman_management', '0011_rename_bank_account_number_premiumcollection_account_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='premiumcollection',
            old_name='bank_account_name',
            new_name='account_name',
        ),
    ]
