# Generated by Django 5.1.4 on 2026-05-02 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesman_management', '0012_rename_bank_account_name_premiumcollection_account_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='premiumcollection',
            name='mfs_provider_name',
        ),
    ]
