# Generated by Django 5.1.4 on 2025-08-07 14:21

import b2bmanagement.models
import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2bmanagement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='commencement_date',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='contract_date',
            new_name='enrollment_date',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='contract_term',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='email',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='management_expense',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='phone_no',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='profit_commision',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='reffered_by',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='renewal_date',
        ),
        migrations.AddField(
            model_name='organization',
            name='account_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='account_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='b2bmanagement.bank'),
        ),
        migrations.AddField(
            model_name='organization',
            name='bin_file',
            field=models.FileField(default=django.utils.timezone.now, upload_to=b2bmanagement.models.bin_file_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='bin_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='branch_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='branch_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='partnership_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='routing_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='tin_file',
            field=models.FileField(default=datetime.datetime(2025, 8, 7, 14, 21, 44, 111957, tzinfo=datetime.timezone.utc), upload_to=b2bmanagement.models.tin_file_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='tin_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='website',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_code',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.CreateModel(
            name='OrganizationContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(blank=True, max_length=150, null=True)),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designations', to='b2bmanagement.designation')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='b2bmanagement.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PartnershipDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partnership_file', models.FileField(upload_to=b2bmanagement.models.document_file_path)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='b2bmanagement.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
