# Generated by Django 5.1.4 on 2025-08-12 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2bmanagement', '0003_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='account_type',
            field=models.CharField(choices=[('bank', 'Bank'), ('mfs', 'MOBILE FINANCIAL SERVICE')], default='nd', max_length=10),
        ),
        migrations.AddField(
            model_name='organization',
            name='contract_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
