# Generated by Django 5.1.4 on 2025-08-12 13:35

import b2bmanagement.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2bmanagement', '0004_bank_account_type_organization_contract_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='bin_file',
            field=models.FileField(blank=True, null=True, upload_to=b2bmanagement.models.bin_file_path),
        ),
        migrations.AlterField(
            model_name='organization',
            name='tin_file',
            field=models.FileField(blank=True, null=True, upload_to=b2bmanagement.models.tin_file_path),
        ),
    ]
