# Generated by Django 5.1.4 on 2025-08-19 10:54

import b2bmanagement.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2bmanagement', '0005_alter_organization_bin_file_and_more'),
        ('b2bproduct', '0004_rename_claim_policy_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='insurer',
            old_name='name',
            new_name='insurer_contract_no',
        ),
        migrations.AddField(
            model_name='insurer',
            name='account_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='insurer',
            name='account_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='insurer',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='insurer',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='b2bmanagement.bank'),
        ),
        migrations.AddField(
            model_name='insurer',
            name='bin_file',
            field=models.FileField(blank=True, null=True, upload_to=b2bmanagement.models.bin_file_path),
        ),
        migrations.AddField(
            model_name='insurer',
            name='bin_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='insurer',
            name='branch_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='insurer',
            name='branch_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='insurer',
            name='insurer_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='insurer',
            name='insurer_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='insurer',
            name='routing_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='insurer',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Active'), (2, 'Inactive')], default=1),
        ),
        migrations.AddField(
            model_name='insurer',
            name='trade_license_file',
            field=models.FileField(blank=True, null=True, upload_to=b2bmanagement.models.tin_file_path),
        ),
        migrations.AddField(
            model_name='insurer',
            name='trade_license_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='insurer',
            name='website',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='InsurerContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(blank=True, max_length=150, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Active'), (2, 'Inactive')], default=1)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_related', to=settings.AUTH_USER_MODEL)),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurer_designations', to='b2bmanagement.designation')),
                ('insurer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurer_contacts', to='b2bmanagement.insurer')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InsurerPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_name', models.CharField(blank=True, max_length=150, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('enrollment_date', models.DateField(blank=True, null=True)),
                ('family_mode', models.PositiveSmallIntegerField(choices=[(1, 'FAMILY_FLOTTER'), (2, 'PER DISABILITY'), (3, 'PER YEAR'), (4, 'PER DECEASE')], default=1)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_related', to=settings.AUTH_USER_MODEL)),
                ('insurer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurer_policies', to='b2bmanagement.insurer')),
                ('policy_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='b2bproduct.product')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'insurer_policy',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='InsurerPolicyDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.FileField(blank=True, null=True, upload_to=b2bmanagement.models.insuert_policy_document_file_path)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_related', to=settings.AUTH_USER_MODEL)),
                ('insurer_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insurer_policy_documents', to='b2bmanagement.insurerpolicy')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'insurer_policy_document',
                'ordering': ['-id'],
            },
        ),
    ]
