# Generated by Django 5.1.4 on 2025-08-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2bmanagement', '0006_rename_name_insurer_insurer_contract_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurerpolicy',
            name='family_mode',
            field=models.PositiveSmallIntegerField(choices=[(1, 'FAMILY FLOTTER'), (2, 'PER DISABILITY'), (3, 'PER YEAR'), (4, 'PER DECEASE')], default=1),
        ),
    ]
