# Generated by Django 5.1.4 on 2025-08-21 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b2bmanagement', '0007_alter_insurerpolicy_family_mode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insurerpolicy',
            old_name='family_mode',
            new_name='policy_mode',
        ),
    ]
