# Generated by Django 5.1.4 on 2025-08-21 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2bmanagement', '0008_rename_family_mode_insurerpolicy_policy_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurer',
            name='insurer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
