# Generated by Django 5.1.4 on 2025-08-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2bmanagement', '0009_alter_insurer_insurer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurer',
            name='insurer_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
