# Generated by Django 5.1.4 on 2025-08-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2bmanagement', '0011_alter_insurer_insurer_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insurercontact',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='insurer',
            name='trade_license_no',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterModelTable(
            name='insurercontact',
            table='insurer_contacts',
        ),
    ]
