# Generated by Django 5.1.4 on 2025-08-22 11:46

import b2bmanagement.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2bmanagement', '0012_alter_insurercontact_options_and_more'),
        ('b2bproduct', '0004_rename_claim_policy_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationcontact',
            options={'ordering': ['-id']},
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='tin_file',
            new_name='trade_license_file',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='contract_no',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='enrollment_date',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='partnership_type',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='tin_number',
        ),
        migrations.AddField(
            model_name='organization',
            name='trade_license_no',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='organizationcontact',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationcontact',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Active'), (2, 'Inactive')], default=1),
        ),
        migrations.AlterField(
            model_name='organizationcontact',
            name='designation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_designations', to='b2bmanagement.designation'),
        ),
        migrations.AlterModelTable(
            name='organizationcontact',
            table='organization_contacts',
        ),
        migrations.CreateModel(
            name='OrganzationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_name', models.CharField(blank=True, max_length=150, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('enrollment_date', models.DateField(blank=True, null=True)),
                ('policy_mode', models.PositiveSmallIntegerField(choices=[(1, 'FAMILY FLOTTER'), (2, 'PER DISABILITY'), (3, 'PER YEAR'), (4, 'PER DECEASE')], default=1)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_related', to=settings.AUTH_USER_MODEL)),
                ('insurer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_insurers', to='b2bmanagement.insurer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_policies', to='b2bmanagement.organization')),
                ('policy_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='b2bproduct.product')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'organization_policy',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationPolicyDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.FileField(blank=True, null=True, upload_to=b2bmanagement.models.organization_policy_document_file_path)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_related', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('organization_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_policy_documents', to='b2bmanagement.organzationpolicy')),
            ],
            options={
                'db_table': 'organization_policy_document',
                'ordering': ['-id'],
            },
        ),
        migrations.DeleteModel(
            name='PartnershipDocuments',
        ),
    ]
