# Generated by Django 5.1.4 on 2025-08-22 12:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b2bmanagement', '0013_alter_organizationcontact_options_and_more'),
        ('b2bproduct', '0004_rename_claim_policy_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrganzationPolicy',
            new_name='OrganizationPolicy',
        ),
    ]
