# Generated by Django 5.1.4 on 2025-08-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2bmanagement', '0014_rename_organzationpolicy_organizationpolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='organization_contract_no',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
