# Generated by Django 5.1.4 on 2025-08-22 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2bmanagement', '0015_organization_organization_contract_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationpolicy',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_policies', to='b2bmanagement.organization'),
        ),
    ]
