# Generated by Django 5.1.4 on 2025-08-22 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b2bmanagement', '0016_alter_organizationpolicy_organization'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ('-id',)},
        ),
    ]
