# Generated by Django 5.1.4 on 2025-08-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2bmanagement', '0017_alter_organization_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurer',
            name='website',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='website',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
