# Generated by Django 5.1.4 on 2025-08-23 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2bmanagement', '0018_alter_insurer_website_alter_organization_website'),
        ('b2bproduct', '0004_rename_claim_policy_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Active'), (2, 'Inactive')], default=1)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_related', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_organizations', to='b2bmanagement.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'company_plans',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CompanyPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coverage_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('premium_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('premium_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('insured_beneficiary_no', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Active'), (2, 'Inactive')], default=1)),
                ('company_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_plans', to='b2bmanagement.companyplan')),
                ('coverage_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='b2bproduct.policy')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_related', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_types', to='b2bmanagement.plan')),
                ('policy_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='b2bproduct.product')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'company_plan_items',
                'ordering': ['-id'],
            },
        ),
    ]
