# Generated by Django 5.1.4 on 2025-08-23 10:12

import b2bmanagement.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2bmanagement', '0019_companyplan_companyplanitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyplanitem',
            name='company_plan_file',
            field=models.FileField(blank=True, null=True, upload_to=b2bmanagement.models.compnay_plan_file_path),
        ),
    ]
