# Generated by Django 5.1.4 on 2025-08-23 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2bmanagement', '0020_companyplanitem_company_plan_file'),
        ('b2bproduct', '0004_rename_claim_policy_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyplanitem',
            name='coverage_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_coverage_types', to='b2bproduct.policy'),
        ),
        migrations.AlterField(
            model_name='companyplanitem',
            name='policy_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_policies', to='b2bproduct.product'),
        ),
    ]
