# Generated by Django 5.1.4 on 2025-08-23 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2bmanagement', '0021_alter_companyplanitem_coverage_type_and_more'),
        ('b2bproduct', '0004_rename_claim_policy_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyplan',
            options={},
        ),
        migrations.RemoveField(
            model_name='companyplan',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='companyplan',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='companyplan',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='companyplanitem',
            name='company_plan',
        ),
        migrations.RemoveField(
            model_name='companyplanitem',
            name='company_plan_file',
        ),
        migrations.RemoveField(
            model_name='companyplanitem',
            name='plan',
        ),
        migrations.AlterField(
            model_name='companyplanitem',
            name='coverage_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='companyplanitem',
            name='coverage_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan_coverage_types', to='b2bproduct.policy'),
        ),
        migrations.AlterField(
            model_name='companyplanitem',
            name='insured_beneficiary_no',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='companyplanitem',
            name='policy_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan_policies', to='b2bproduct.product'),
        ),
        migrations.AlterField(
            model_name='companyplanitem',
            name='premium_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='companyplanitem',
            name='premium_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='companyplanitem',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterModelTable(
            name='companyplan',
            table=None,
        ),
    ]
