# Generated by Django 5.1.4 on 2025-08-26 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2bmanagement', '0023_alter_companyplan_options_companyplan_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyplandocument',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='insurer',
            name='trade_license_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='trade_license_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
