# Generated by Django 5.1.4 on 2025-08-28 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2bmanagement', '0024_alter_companyplandocument_options_alter_plan_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationcontact',
            name='designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_designations', to='b2bmanagement.designation'),
        ),
    ]
