# Generated by Django 5.1.4 on 2025-08-28 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2bmanagement', '0025_alter_organizationcontact_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurercontact',
            name='designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insurer_designations', to='b2bmanagement.designation'),
        ),
    ]
