# Generated by Django 5.1.4 on 2025-08-28 11:55

import b2bmanagement.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2bmanagement', '0026_alter_insurercontact_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurer',
            name='company_logo',
            field=models.FileField(blank=True, null=True, upload_to=b2bmanagement.models.compnay_logo_path),
        ),
        migrations.AddField(
            model_name='organization',
            name='company_logo',
            field=models.FileField(blank=True, null=True, upload_to=b2bmanagement.models.compnay_logo_path),
        ),
    ]
