# Generated by Django 5.1.4 on 2025-08-28 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2bmanagement', '0027_insurer_company_logo_organization_company_logo'),
        ('b2bproduct', '0004_rename_claim_policy_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurer',
            name='insurer_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='b2bproduct.product'),
        ),
    ]
