# Generated by Django 5.1.4 on 2025-08-28 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2bmanagement', '0028_insurer_insurer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurerpolicy',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Active'), (2, 'Inactive')], default=1),
        ),
        migrations.AlterField(
            model_name='bank',
            name='account_type',
            field=models.CharField(choices=[('bank', 'Bank'), ('mfs', 'MOBILE FINANCIAL SERVICE')], default='bank', max_length=10),
        ),
    ]
