# Generated by Django 5.1.4 on 2025-08-29 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2bmanagement', '0029_insurerpolicy_status_alter_bank_account_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insurerpolicy',
            old_name='policy_name',
            new_name='contract_title',
        ),
        migrations.RemoveField(
            model_name='insurer',
            name='insurer_contract_no',
        ),
        migrations.AddField(
            model_name='insurerpolicy',
            name='insurer_contract_no',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
