# Generated by Django 5.1.4 on 2025-08-30 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b2bmanagement', '0030_rename_policy_name_insurerpolicy_contract_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurer',
            name='insurer_type',
        ),
    ]
