# Generated by Django 5.1.4 on 2025-08-31 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2bmanagement', '0031_remove_insurer_insurer_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyplan',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='organization_contract_no',
        ),
        migrations.AddField(
            model_name='companyplan',
            name='organization_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_plan_policies', to='b2bmanagement.organizationpolicy'),
        ),
        migrations.AddField(
            model_name='organizationpolicy',
            name='organization_contract_no',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
