# Generated by Django 5.1.4 on 2025-09-02 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b2bmanagement', '0032_remove_companyplan_organization_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizationpolicy',
            old_name='policy_name',
            new_name='contract_title',
        ),
    ]
