# Generated by Django 5.1.4 on 2025-09-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2bmanagement', '0033_rename_policy_name_organizationpolicy_contract_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationpolicy',
            name='policy_mode',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'FAMILY FLOTTER'), (2, 'PER DISABILITY'), (3, 'PER YEAR'), (4, 'PER DECEASE')], default=1, null=True),
        ),
    ]
