# Generated by Django 5.1.4 on 2025-09-02 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2bmanagement', '0034_alter_organizationpolicy_policy_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='company_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Life'), (2, 'Non-Life')], default=1),
        ),
    ]
