# Generated by Django 5.1.4 on 2025-09-02 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2bmanagement', '0035_organization_company_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='company_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Life'), (2, 'Non-Life')], default=1, null=True),
        ),
    ]
