# Generated by Django 5.1.4 on 2025-09-03 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2bmanagement', '0036_alter_organization_company_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyplanitem',
            name='company_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_plan_items', to='b2bmanagement.companyplandocument'),
        ),
    ]
