# Generated by Django 5.1.4 on 2025-09-07 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b2bmanagement', '0037_alter_companyplanitem_company_document'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationpolicy',
            options={'ordering': ['id']},
        ),
    ]
