# Generated by Django 5.1.4 on 2025-09-07 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2bmanagement', '0038_alter_organizationpolicy_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationpolicy',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Active'), (2, 'Inactive')], default=1),
        ),
    ]
