# Generated by Django 5.1.4 on 2025-11-29 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2bmanagement', '0041_district'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurer',
            name='company_type',
        ),
        migrations.AddField(
            model_name='insurer',
            name='insurer_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Life'), (2, 'Non Life')], default=1),
        ),
        migrations.AlterField(
            model_name='organization',
            name='company_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Life'), (2, 'Non Life')], default=1, null=True),
        ),
    ]
