# Generated by Django 5.1.4 on 2025-12-08 06:31

import b2bmanagement.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2bmanagement', '0043_alter_organization_company_type_hospitalinformation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GopIormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_cabin_word_no', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('date_of_admission', models.DateField(blank=True, null=True)),
                ('attendant_name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('document', models.FileField(blank=True, null=True, upload_to=b2bmanagement.models.advice_file_path)),
                ('attendant_mobile', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('diagnosis', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('attendant_relation', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('gop', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Completed')], default=1)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_related', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospitals', to='b2bmanagement.hospitalinformation')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gop_information',
                'ordering': ['-id'],
            },
        ),
    ]
