# Generated by Django 5.1.4 on 2025-12-08 06:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b2bmanagement', '0044_gopiormation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GopIormation',
            new_name='GopInformation',
        ),
    ]
