# Generated by Django 5.1.4 on 2025-12-08 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2bmanagement', '0045_rename_gopiormation_gopinformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gopinformation',
            name='attendant_mobile',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='gopinformation',
            name='attendant_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gopinformation',
            name='attendant_relation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gopinformation',
            name='bed_cabin_word_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='gopinformation',
            name='diagnosis',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='gopinformation',
            name='gop',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
