# Generated by Django 5.1.4 on 2026-01-27 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2bmanagement', '0046_alter_gopinformation_attendant_mobile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='company_type',
        ),
        migrations.AlterField(
            model_name='organization',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='b2bmanagement.bank'),
        ),
    ]
