# Generated by Django 5.1.4 on 2026-01-27 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2bmanagement', '0047_remove_organization_company_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='company_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='b2bmanagement.companytype'),
        ),
    ]
