# Generated by Django 5.1.4 on 2026-01-28 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2bmanagement', '0048_organization_company_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='b2bmanagement.bank'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='company_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='b2bmanagement.companytype'),
        ),
    ]
