# Generated by Django 5.1.4 on 2026-02-03 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2bmanagement', '0049_alter_organization_bank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyplanitem',
            name='premium_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
