# Generated by Django 5.1.4 on 2026-02-04 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b2bmanagement', '0050_alter_companyplanitem_premium_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurerpolicy',
            name='policy_mode',
        ),
        migrations.RemoveField(
            model_name='insurerpolicy',
            name='policy_type',
        ),
        migrations.RemoveField(
            model_name='organizationpolicy',
            name='policy_mode',
        ),
        migrations.RemoveField(
            model_name='organizationpolicy',
            name='policy_type',
        ),
    ]
