# Generated by Django 5.1.4 on 2026-02-04 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2bmanagement', '0051_remove_insurerpolicy_policy_mode_and_more'),
        ('b2bproduct', '0004_rename_claim_policy_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurerpolicy',
            name='policy_mode',
            field=models.PositiveSmallIntegerField(choices=[(1, 'FAMILY FLOTTER'), (2, 'PER DISABILITY'), (3, 'PER YEAR'), (4, 'PER DECEASE')], default=1),
        ),
        migrations.AddField(
            model_name='insurerpolicy',
            name='policy_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='b2bproduct.product'),
        ),
    ]
