# Generated by Django 5.1.4 on 2026-04-29 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2bmanagement', '0053_branch'),
        ('salesman_management', '0002_salesemployee_organization_sales_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationSalesPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Active'), (2, 'Inactive')], default=1)),
                ('organization_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_sales_polices', to='b2bmanagement.organizationpolicy')),
                ('sales_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_sales_persons', to='salesman_management.salesemployee')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
