# Generated by Django 5.1.4 on 2026-05-02 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2bmanagement', '0054_organizationsalesperson'),
        ('salesman_management', '0008_remove_overridecommission_policy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='sales_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_sales_persons', to='salesman_management.salesemployee'),
        ),
        migrations.DeleteModel(
            name='OrganizationSalesPerson',
        ),
    ]
