# Generated by Django 5.1.4 on 2026-05-02 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2bmanagement', '0055_organization_sales_employee_and_more'),
        ('salesman_management', '0009_remove_premiumcollection_commision_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='account_type',
            field=models.CharField(choices=[('bank', 'Bank'), ('cash', 'Cash'), ('mfs', 'MOBILE FINANCIAL SERVICE')], default='bank', max_length=10),
        ),
        migrations.AlterField(
            model_name='organization',
            name='sales_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_sales_person', to='salesman_management.salesemployee'),
        ),
    ]
