# Generated by Django 5.1.4 on 2025-08-08 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiaryinformation',
            name='number',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiaryinformation',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
