# Generated by Django 5.1.4 on 2025-08-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0003_alter_beneficiaryinformation_ci_sum_assured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiaryinformation',
            name='benificiary_type',
            field=models.CharField(choices=[('sb', 'SINGLE BENIFIT'), ('fb', 'FAMILY BENIFIT')], default='sb', max_length=10),
        ),
        migrations.AddField(
            model_name='claiminformation',
            name='creation_from',
            field=models.PositiveBigIntegerField(choices=[(1, 'WEB'), (2, 'MObile APP')], default=1),
        ),
        migrations.AlterField(
            model_name='claiminformation',
            name='beneficiary_type',
            field=models.CharField(choices=[('sb', 'SINGLE BENIFIT'), ('fb', 'FAMILY BENIFIT')], default='nd', max_length=10),
        ),
    ]
