# Generated by Django 5.1.4 on 2025-08-10 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0004_beneficiaryinformation_benificiary_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claiminformation',
            name='death_cause',
            field=models.TextField(blank=True, null=True),
        ),
    ]
