# Generated by Django 5.1.4 on 2025-08-10 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0005_claiminformation_death_cause'),
    ]

    operations = [
        migrations.AddField(
            model_name='claiminformation',
            name='death_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
