# Generated by Django 5.1.4 on 2025-08-10 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0007_alter_claiminformation_ancillary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claiminformation',
            name='beneficiary_type',
            field=models.CharField(choices=[('nd', 'NATURAL DEATH'), ('ad', 'ACCIDENTAL DEATH'), ('ptd', 'PERMANENT TOTAL DISABILITY'), ('pd', 'PARTIAL DISABILITY'), ('hipd', 'HEALTH - IPD'), ('hopd', 'HEALTH - OPD'), ('hm', 'HEALTH - MATERNITY'), ('hdc', 'HEALTH - DAYCARE'), ('hopdo', 'HEALTH - OPD - OPTICAL'), ('hopdd', 'HEALTH - OPD - DENTAL')], default='nd', max_length=10),
        ),
    ]
