# Generated by Django 5.1.4 on 2025-08-10 08:47

import claim.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0009_alter_filetransfer_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimdocuments',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=claim.models.document_file_path),
        ),
        migrations.AlterField(
            model_name='claimdocuments',
            name='document_type',
            field=models.CharField(blank=True, choices=[('drc', 'DEATH REGISTRATION CERTIFICATE'), ('dcfh', 'DEATH CERTIFICATE FROM HOSPITAL'), ('cnnph', 'COPY OF NID OF NOMINEE & POLICY HOLDER'), ('hdc', 'HOSPITAL DISCHARGE CERTIFICATE'), ('dp', 'DOCTOR’S PRESCRIPTIONS'), ('dr', 'DIAGNOSIS REPORTS'), ('hb', 'HOSPITAL BILLS'), ('fad', 'FIR FOR ACCIDENTAL DEATH'), ('nbad', 'NOMINEE BANK ACCOUNT DETAILS'), ('gs/lt', 'GRAVEYARD SLIP / LOCAL TESTIMONIAL'), ('dl', 'DIVERSE LICENSE')], default='drc', max_length=10, null=True),
        ),
    ]
