# Generated by Django 5.1.4 on 2025-08-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0010_alter_claimdocuments_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claiminformation',
            name='funeral_expense',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
