# Generated by Django 5.1.4 on 2025-08-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0011_claiminformation_funeral_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='claiminformation',
            name='investigation_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='claiminformation',
            name='outstanding_medical_bill',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
