# Generated by Django 5.1.4 on 2025-08-10 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('claim', '0012_claiminformation_investigation_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filetransfer',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_from_dept', to='auth.group'),
        ),
    ]
