# Generated by Django 5.1.4 on 2025-08-10 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('claim', '0013_filetransfer_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filetransfer',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_group', to='auth.group'),
        ),
    ]
