# Generated by Django 5.1.4 on 2025-08-10 14:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('b2bmanagement', '0003_department'),
        ('claim', '0014_alter_filetransfer_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FileTransfer',
            new_name='FileTransferHistory',
        ),
        migrations.AlterModelOptions(
            name='filetransferhistory',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelTable(
            name='filetransferhistory',
            table='file_transfer_history',
        ),
    ]
