# Generated by Django 5.1.4 on 2025-08-10 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0015_rename_filetransfer_filetransferhistory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimdocuments',
            name='claim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='claim.claiminformation'),
        ),
    ]
