# Generated by Django 5.1.4 on 2025-08-10 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0016_alter_claimdocuments_claim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filetransferhistory',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='claim.claiminformation'),
        ),
    ]
