# Generated by Django 5.1.4 on 2025-08-12 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0018_alter_filetransferhistory_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beneficiaryinformation',
            old_name='ci_sum_assured',
            new_name='sum_assured_life',
        ),
        migrations.RemoveField(
            model_name='beneficiaryinformation',
            name='comm_tate',
        ),
        migrations.RemoveField(
            model_name='beneficiaryinformation',
            name='dental_limit',
        ),
        migrations.RemoveField(
            model_name='beneficiaryinformation',
            name='dental_premium',
        ),
        migrations.RemoveField(
            model_name='beneficiaryinformation',
            name='health_premium',
        ),
        migrations.RemoveField(
            model_name='beneficiaryinformation',
            name='ipd_limit',
        ),
        migrations.RemoveField(
            model_name='beneficiaryinformation',
            name='life_premium',
        ),
        migrations.RemoveField(
            model_name='beneficiaryinformation',
            name='maternity_limit',
        ),
        migrations.RemoveField(
            model_name='beneficiaryinformation',
            name='maternity_premium',
        ),
        migrations.RemoveField(
            model_name='beneficiaryinformation',
            name='opd_limit',
        ),
        migrations.RemoveField(
            model_name='beneficiaryinformation',
            name='opd_premium',
        ),
        migrations.RemoveField(
            model_name='beneficiaryinformation',
            name='optical_limit',
        ),
        migrations.RemoveField(
            model_name='beneficiaryinformation',
            name='optical_premium',
        ),
        migrations.RemoveField(
            model_name='beneficiaryinformation',
            name='overseas_treatment_limit',
        ),
        migrations.RemoveField(
            model_name='beneficiaryinformation',
            name='renew_date',
        ),
        migrations.RemoveField(
            model_name='beneficiaryinformation',
            name='sum_assured',
        ),
        migrations.RemoveField(
            model_name='beneficiaryinformation',
            name='supplementary_premium',
        ),
        migrations.RemoveField(
            model_name='beneficiaryinformation',
            name='total_premium',
        ),
        migrations.AddField(
            model_name='beneficiaryinformation',
            name='ac_type',
            field=models.CharField(choices=[('bank', 'Bank'), ('mw', 'Mobile Wallet')], default='mw', max_length=10),
        ),
        migrations.AddField(
            model_name='beneficiaryinformation',
            name='nominee_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='beneficiaryinformation',
            name='org_Code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='claiminformation',
            name='file_status',
            field=models.PositiveBigIntegerField(choices=[(0, 'DECLINED'), (1, 'APPROVED'), (2, 'SUBMITTED'), (3, 'SETTELED'), (4, 'PENDING'), (5, 'PROCESSING')], default=4),
        ),
    ]
