# Generated by Django 5.1.4 on 2025-08-12 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2bmanagement', '0004_bank_account_type_organization_contract_no'),
        ('claim', '0019_rename_ci_sum_assured_beneficiaryinformation_sum_assured_life_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiaryinformation',
            name='contract_no',
        ),
        migrations.RemoveField(
            model_name='beneficiaryinformation',
            name='org_Code',
        ),
        migrations.RemoveField(
            model_name='beneficiaryinformation',
            name='organization_name',
        ),
        migrations.AddField(
            model_name='beneficiaryinformation',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to='b2bmanagement.organization'),
        ),
        migrations.AlterField(
            model_name='beneficiaryinformation',
            name='marital_status',
            field=models.CharField(choices=[('S', 'Single'), ('M', 'Married'), ('D', 'Divorced'), ('W', 'Widowed')], default='single', max_length=10),
        ),
    ]
