# Generated by Django 5.1.4 on 2025-08-12 08:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b2bmanagement', '0004_bank_account_type_organization_contract_no'),
        ('claim', '0020_remove_beneficiaryinformation_contract_no_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BeneficiaryInformation',
            new_name='EmployeeInformation',
        ),
        migrations.RenameField(
            model_name='claiminformation',
            old_name='beneficiary',
            new_name='employee',
        ),
    ]
