# Generated by Django 5.1.4 on 2025-08-12 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0021_rename_beneficiaryinformation_employeeinformation_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employeeinformation',
            table='employee_information',
        ),
    ]
