# Generated by Django 5.1.4 on 2025-08-12 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2bmanagement', '0005_alter_organization_bin_file_and_more'),
        ('claim', '0022_alter_employeeinformation_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeinformation',
            name='contract_no',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='employeeinformation',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='b2bmanagement.plan'),
        ),
    ]
