# Generated by Django 5.1.4 on 2025-08-13 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0023_employeeinformation_contract_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeinformation',
            name='nominee_type',
            field=models.CharField(choices=[('y', 'YES'), ('n', 'No')], default='n', max_length=5),
        ),
        migrations.AlterField(
            model_name='employeeinformation',
            name='ac_type',
            field=models.CharField(choices=[('bank', 'Bank'), ('mfs', 'Mobile Financial Service')], default='mfs', max_length=10),
        ),
    ]
