# Generated by Django 5.1.4 on 2025-08-13 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0024_employeeinformation_nominee_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claiminformation',
            name='currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
