# Generated by Django 5.1.4 on 2025-08-14 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0025_claiminformation_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claiminformation',
            name='beneficiary_type',
            field=models.CharField(choices=[('nd', 'NATURAL DEATH'), ('ad', 'ACCIDENTAL DEATH'), ('ptd', 'PERMANENT TOTAL DISABILITY'), ('pd', 'PARTIAL DISABILITY'), ('hipd', 'HEALTH - IPD'), ('hopd', 'HEALTH - OPD'), ('hm', 'HEALTH - MATERNITY'), ('hdc', 'HEALTH - DAYCARE'), ('hopdo', 'HEALTH - OPD - OPTICAL'), ('hopdd', 'HEALTH - OPD - DENTAL'), ('hci', 'CRTICAL ILLNESS')], default='nd', max_length=10),
        ),
        migrations.AlterField(
            model_name='claiminformation',
            name='creation_from',
            field=models.PositiveBigIntegerField(choices=[(1, 'WEB'), (2, 'Mobile APP')], default=1),
        ),
    ]
