# Generated by Django 5.1.4 on 2025-08-14 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0026_alter_claiminformation_beneficiary_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeinformation',
            name='hr_type',
            field=models.CharField(choices=[('y', 'YES'), ('n', 'No')], default='n', max_length=5),
        ),
        migrations.AddField(
            model_name='employeeinformation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
