# Generated by Django 5.1.4 on 2025-08-15 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0028_claiminformation_current_holder_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filetransferhistory',
            name='status',
        ),
    ]
