# Generated by Django 5.1.4 on 2025-08-15 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0029_remove_filetransferhistory_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='filetransferhistory',
            name='status',
            field=models.PositiveBigIntegerField(choices=[(0, 'DECLINED'), (1, 'APPROVED'), (2, 'SUBMITTED'), (3, 'SETTELED'), (4, 'PENDING'), (5, 'PROCESSING')], default=4),
        ),
    ]
