# Generated by Django 5.1.4 on 2025-08-17 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2bproduct', '0003_policy'),
        ('claim', '0031_alter_claiminformation_file_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claiminformation',
            name='claim_for',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='claiminformation',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='b2bproduct.policy'),
        ),
        migrations.AddField(
            model_name='claiminformation',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='b2bproduct.product'),
        ),
    ]
