# Generated by Django 5.1.4 on 2025-08-17 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0032_claiminformation_claim_for_claiminformation_policy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claiminformation',
            name='beneficiary_type',
        ),
        migrations.RemoveField(
            model_name='claiminformation',
            name='claim_type',
        ),
    ]
