# Generated by Django 5.1.4 on 2025-08-27 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0033_remove_claiminformation_beneficiary_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claiminformation',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_claim_files', to='claim.employeeinformation'),
        ),
        migrations.AlterField(
            model_name='claiminformation',
            name='file_status',
            field=models.PositiveBigIntegerField(choices=[(0, 'DECLINED'), (1, 'APPROVED'), (2, 'SUBMITTED'), (3, 'SETTELED'), (4, 'PENDING'), (5, 'PROCESSING'), (6, 'RETURN'), (7, 'DOCUMENT WANTED')], default=4),
        ),
        migrations.AlterField(
            model_name='filetransferhistory',
            name='status',
            field=models.PositiveBigIntegerField(choices=[(0, 'DECLINED'), (1, 'APPROVED'), (2, 'SUBMITTED'), (3, 'SETTELED'), (4, 'PENDING'), (5, 'PROCESSING'), (6, 'RETURN'), (7, 'DOCUMENT WANTED')], default=4),
        ),
    ]
