# Generated by Django 5.1.4 on 2025-08-27 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0035_alter_claiminformation_file_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claiminformation',
            name='file_status',
            field=models.PositiveBigIntegerField(choices=[(0, 'DECLINED'), (1, 'APPROVED'), (2, 'SUBMITTED'), (3, 'SETTELED'), (4, 'PENDING'), (5, 'PROCESSING'), (6, 'RETURN'), (7, 'DOCUMENT-WANTED')], default=4),
        ),
        migrations.AlterField(
            model_name='filetransferhistory',
            name='status',
            field=models.PositiveBigIntegerField(choices=[(0, 'DECLINED'), (1, 'APPROVED'), (2, 'SUBMITTED'), (3, 'SETTELED'), (4, 'PENDING'), (5, 'PROCESSING'), (6, 'RETURN'), (7, 'DOCUMENT-WANTED')], default=4),
        ),
    ]
