# Generated by Django 5.1.4 on 2025-08-31 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2bmanagement', '0032_remove_companyplan_organization_and_more'),
        ('claim', '0036_alter_claiminformation_file_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeinformation',
            name='organization',
        ),
        migrations.AddField(
            model_name='employeeinformation',
            name='organization_emp_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emp_policy_organizations', to='b2bmanagement.organizationpolicy'),
        ),
    ]
