# Generated by Django 5.1.4 on 2025-09-02 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0037_remove_employeeinformation_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeinformation',
            name='relation',
            field=models.CharField(choices=[('self', 'Self'), ('child', 'Child-1'), ('child2', 'Child-2'), ('child3', 'Child-3'), ('child4', 'Child-4'), ('child5', 'Child-5'), ('child6', 'Child-6'), ('father', 'Father'), ('mother', 'Mother'), ('brother', 'Brother'), ('sister', 'Sister'), ('spouse', 'Spouse'), ('son', 'Son'), ('daughter', 'Daughter'), ('friend', 'Friend'), ('relative', 'Relative'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
