# Generated by Django 5.1.4 on 2025-10-06 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('claim', '0039_alter_employeeinformation_relation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claiminformation',
            name='date_of_treatment',
        ),
        migrations.AddField(
            model_name='claiminformation',
            name='current_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holding_claims', to='auth.group'),
        ),
        migrations.AddField(
            model_name='filetransferhistory',
            name='from_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_claims', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='claimdocuments',
            name='document_type',
            field=models.CharField(blank=True, choices=[('drc', 'DEATH REGISTRATION CERTIFICATE'), ('dcfh', 'DEATH CERTIFICATE FROM HOSPITAL'), ('cnnph', 'COPY OF NID OF NOMINEE & POLICY HOLDER'), ('hdc', 'HOSPITAL DISCHARGE CERTIFICATE'), ('dp', 'DOCTOR’S PRESCRIPTIONS'), ('dr', 'DIAGNOSIS REPORTS'), ('hb', 'HOSPITAL BILLS'), ('fad', 'FIR FOR ACCIDENTAL DEATH'), ('nbad', 'NOMINEE BANK ACCOUNT DETAILS'), ('gs/lt', 'GRAVEYARD SLIP / LOCAL TESTIMONIAL'), ('dl', 'DIVERSE LICENSE'), ('all', 'ALL DOCUMENTS')], default='drc', max_length=10, null=True),
        ),
    ]
