# Generated by Django 5.1.4 on 2025-10-08 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0040_remove_claiminformation_date_of_treatment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claiminformation',
            name='date_of_treatment',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='claiminformation',
            name='file_status',
            field=models.PositiveBigIntegerField(choices=[(0, 'DECLINED'), (1, 'APPROVED'), (2, 'SUBMITTED'), (3, 'SETTELED'), (4, 'PENDING'), (5, 'PROCESSING'), (6, 'RETURN'), (7, 'DOCUMENT-REQUIRED')], default=4),
        ),
        migrations.AlterField(
            model_name='filetransferhistory',
            name='status',
            field=models.PositiveBigIntegerField(choices=[(0, 'DECLINED'), (1, 'APPROVED'), (2, 'SUBMITTED'), (3, 'SETTELED'), (4, 'PENDING'), (5, 'PROCESSING'), (6, 'RETURN'), (7, 'DOCUMENT-REQUIRED')], default=4),
        ),
    ]
