# Generated by Django 5.1.4 on 2025-10-09 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0041_claiminformation_date_of_treatment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(choices=[('HR', 'Organization HR'), ('WAADAA', 'Waadaa'), ('INSURER_CLAIM_OFFICER', 'Insurer Claim Officer'), ('INSURER_AUDIT_OFFICER', 'Insurer Audit Officer')], max_length=50)),
                ('action', models.CharField(choices=[('APPROVED', 'Approved'), ('DOCUMENT_REQUIRED', 'Document Required'), ('DECLINED', 'Declined')], max_length=50)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('settled_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_steps', to='claim.claiminformation')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'claim_workflow',
                'ordering': ['-created_at'],
            },
        ),
    ]
