# Generated by Django 5.1.4 on 2025-10-10 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0042_claimworkflow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claiminformation',
            name='current_group',
        ),
        migrations.RemoveField(
            model_name='filetransferhistory',
            name='from_group',
        ),
        migrations.AlterField(
            model_name='claimdocuments',
            name='document_type',
            field=models.CharField(blank=True, choices=[('drc', 'DEATH REGISTRATION CERTIFICATE'), ('dcfh', 'DEATH CERTIFICATE FROM HOSPITAL'), ('cnnph', 'COPY OF NID OF NOMINEE & POLICY HOLDER'), ('hdc', 'HOSPITAL DISCHARGE CERTIFICATE'), ('dp', 'DOCTOR’S PRESCRIPTIONS'), ('dr', 'DIAGNOSIS REPORTS'), ('hb', 'HOSPITAL BILLS'), ('fad', 'FIR FOR ACCIDENTAL DEATH'), ('nbad', 'NOMINEE BANK ACCOUNT DETAILS'), ('gs/lt', 'GRAVEYARD SLIP / LOCAL TESTIMONIAL'), ('dl', 'DIVERSE LICENSE')], default='drc', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='claiminformation',
            name='file_status',
            field=models.PositiveBigIntegerField(choices=[(0, 'DECLINED'), (1, 'APPROVED'), (2, 'SUBMITTED'), (3, 'SETTELED'), (4, 'PENDING'), (5, 'PROCESSING'), (6, 'RETURN'), (7, 'DOCUMENT-WANTED')], default=4),
        ),
        migrations.AlterField(
            model_name='filetransferhistory',
            name='status',
            field=models.PositiveBigIntegerField(choices=[(0, 'DECLINED'), (1, 'APPROVED'), (2, 'SUBMITTED'), (3, 'SETTELED'), (4, 'PENDING'), (5, 'PROCESSING'), (6, 'RETURN'), (7, 'DOCUMENT-WANTED')], default=4),
        ),
        migrations.DeleteModel(
            name='ClaimWorkflow',
        ),
    ]
