# Generated by Django 5.1.4 on 2025-10-10 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('claim', '0043_remove_claiminformation_current_group_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filetransferhistory',
            old_name='group',
            new_name='to_group',
        ),
        migrations.AddField(
            model_name='claiminformation',
            name='current_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_group', to='auth.group'),
        ),
        migrations.AddField(
            model_name='filetransferhistory',
            name='from_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_group', to='auth.group'),
        ),
    ]
