# Generated by Django 5.1.4 on 2025-10-10 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0044_rename_group_filetransferhistory_to_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filetransferhistory',
            name='status_after',
            field=models.PositiveBigIntegerField(choices=[(0, 'DECLINED'), (1, 'APPROVED'), (2, 'SUBMITTED'), (3, 'SETTELED'), (4, 'PENDING'), (5, 'PROCESSING'), (6, 'RETURN'), (7, 'DOCUMENT-WANTED')], default=4),
        ),
        migrations.AddField(
            model_name='filetransferhistory',
            name='status_before',
            field=models.PositiveBigIntegerField(choices=[(0, 'DECLINED'), (1, 'APPROVED'), (2, 'SUBMITTED'), (3, 'SETTELED'), (4, 'PENDING'), (5, 'PROCESSING'), (6, 'RETURN'), (7, 'DOCUMENT-WANTED')], default=4),
        ),
    ]
