# Generated by Django 5.1.4 on 2025-10-11 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0045_filetransferhistory_status_after_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimCostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('claimed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('claims_operation_settled', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('claims_operation_deduction', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('audit_settled', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('audit_deduction', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('remarks_audit', models.TextField(blank=True, null=True)),
                ('remarks_claims_operation', models.TextField(blank=True, null=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_items', to='claim.claiminformation')),
            ],
            options={
                'db_table': 'claim_cost_item',
            },
        ),
    ]
