# Generated by Django 5.1.4 on 2025-10-14 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0046_claimcostitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='claiminformation',
            name='is_edited_audit_officer',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='claiminformation',
            name='is_edited_claim_officer',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='claiminformation',
            name='is_edited_waada',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
