# Generated by Django 5.1.4 on 2025-10-14 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0047_claiminformation_is_edited_audit_officer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claimcostitem',
            name='item_name',
        ),
    ]
