# Generated by Django 5.1.4 on 2025-10-14 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0048_remove_claimcostitem_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimcostitem',
            name='key',
            field=models.CharField(blank=True, choices=[('icu_or_ccu_or_nsu', 'ICU/CCU/NSU'), ('consultation_fee', 'Consultation Fee'), ('medical_investigation', 'Medical Investigation'), ('ancillary', 'Ancillary'), ('medicine', 'Medicine'), ('other', 'Other'), ('package_cost', 'Package Cost'), ('room_rent_1', 'Room Rent1'), ('day_care_amount', 'Day Care Amount'), ('outstanding_medical_bill', 'Outstanding Medical Bills'), ('funeral_expense', 'Funeral Expenses')], max_length=50, null=True),
        ),
    ]
