# Generated by Django 5.1.4 on 2025-10-16 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0050_alter_claimcostitem_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='claiminformation',
            name='is_paid_by_claim',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
