# Generated by Django 5.1.4 on 2025-10-18 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0051_claiminformation_is_paid_by_claim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimcostitem',
            name='key',
            field=models.CharField(blank=True, choices=[('icu_or_ccu_or_nsu', 'ICU/CCU/NSU'), ('consultation_fee', 'Consultation fee'), ('medical_investigation', 'Medical Investigation'), ('ancillary', 'Ancillary'), ('medicine', 'Medicine'), ('other', 'Other'), ('package_cost', 'Package Cost'), ('room_rent_1', 'Room Rent1'), ('day_care_amount', 'Day Care Amount'), ('outstanding_medical_bills', 'Outstanding Medical Bills'), ('funeral_expenses', 'Funeral Expenses')], max_length=50, null=True),
        ),
    ]
