# Generated by Django 5.1.4 on 2025-10-19 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0052_alter_claimcostitem_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimdocuments',
            name='document_type',
            field=models.CharField(blank=True, choices=[('drc', 'DEATH REGISTRATION CERTIFICATE'), ('dcfh', 'DEATH CERTIFICATE FROM HOSPITAL'), ('cnnph', 'COPY OF NID OF NOMINEE & POLICY HOLDER'), ('hdc', 'HOSPITAL DISCHARGE CERTIFICATE'), ('dp', 'DOCTOR’S PRESCRIPTIONS'), ('dr', 'DIAGNOSIS REPORTS'), ('hb', 'HOSPITAL BILLS'), ('fad', 'FIR FOR ACCIDENTAL DEATH'), ('nbad', 'NOMINEE BANK ACCOUNT DETAILS'), ('gs/lt', 'GRAVEYARD SLIP / LOCAL TESTIMONIAL'), ('dl', 'DIVERSE LICENSE'), ('all', 'All Documents')], default='all', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='claiminformation',
            name='icu_or_ccu_or_nsu',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
