# Generated by Django 5.1.4 on 2025-10-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0053_alter_claimdocuments_document_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimcostitem',
            name='key',
            field=models.CharField(blank=True, choices=[('icu_or_ccu_or_nsu', 'ICU/CCU/NSU'), ('consultation_fee', 'Consultation fee'), ('medical_investigation', 'Medical Investigation'), ('investigation_fee', 'Investigation Fee'), ('ancillary', 'Ancillary'), ('medicine', 'Medicine'), ('other', 'Other'), ('others', 'others'), ('package_cost', 'Package Cost'), ('room_rent1', 'Room Rent1'), ('room_rent', 'Room Rent'), ('day_care_amount', 'Day Care Amount'), ('outstanding_medical_bills', 'Outstanding Medical Bills'), ('funeral_expenses', 'Funeral Expenses')], max_length=50, null=True),
        ),
    ]
