# Generated by Django 5.1.4 on 2025-11-06 04:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0054_alter_claimcostitem_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claiminformation',
            name='ancillary',
        ),
        migrations.RemoveField(
            model_name='claiminformation',
            name='claim_amount',
        ),
        migrations.RemoveField(
            model_name='claiminformation',
            name='consultation_fee',
        ),
        migrations.RemoveField(
            model_name='claiminformation',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='claiminformation',
            name='day_care_amount',
        ),
        migrations.RemoveField(
            model_name='claiminformation',
            name='funeral_expense',
        ),
        migrations.RemoveField(
            model_name='claiminformation',
            name='icu_or_ccu_or_nsu',
        ),
        migrations.RemoveField(
            model_name='claiminformation',
            name='investigation_fee',
        ),
        migrations.RemoveField(
            model_name='claiminformation',
            name='maternity_legal_abortion',
        ),
        migrations.RemoveField(
            model_name='claiminformation',
            name='maternity_lucs_cesarean',
        ),
        migrations.RemoveField(
            model_name='claiminformation',
            name='medical_investigation',
        ),
        migrations.RemoveField(
            model_name='claiminformation',
            name='medicine',
        ),
        migrations.RemoveField(
            model_name='claiminformation',
            name='meternity_nvd_or_normal_delivery',
        ),
        migrations.RemoveField(
            model_name='claiminformation',
            name='others',
        ),
        migrations.RemoveField(
            model_name='claiminformation',
            name='outstanding_medical_bill',
        ),
        migrations.RemoveField(
            model_name='claiminformation',
            name='package_cost',
        ),
        migrations.RemoveField(
            model_name='claiminformation',
            name='romm_package_cost',
        ),
        migrations.RemoveField(
            model_name='claiminformation',
            name='room_rent_1',
        ),
        migrations.RemoveField(
            model_name='claiminformation',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='claiminformation',
            name='claim_type',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name=[(1, 'Meternity NVD/Normal delivery'), (2, 'Maternity LUCS Cesarean'), (3, 'Maternity Legal abortion')]),
        ),
        migrations.AddField(
            model_name='claiminformation',
            name='death_of_departure',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claiminformation',
            name='hospital_clinic_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claiminformation',
            name='is_other_description',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='claimcostitem',
            name='key',
            field=models.CharField(blank=True, choices=[('icu_or_ccu_or_nsu', 'ICU/CCU/NSU'), ('consultation_fee', 'Consultation fee'), ('medical_investigation', 'Medical Investigation'), ('investigation_fee', 'Investigation Fee'), ('ancillary', 'Ancillary'), ('medicine', 'Medicine'), ('other', 'Other'), ('others', 'others'), ('package_cost', 'Package Cost'), ('room_rent1', 'Room Rent1'), ('room_rent', 'Room Rent'), ('day_care_amount', 'Day Care Amount'), ('outstanding_medical_bills', 'Outstanding Medical Bills'), ('funeral_expenses', 'Funeral Expenses'), ('surgery', 'Surgery')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('symbol', models.CharField(blank=True, max_length=5, null=True)),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=1.0, max_digits=12)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'currencies',
                'db_table': 'currency',
            },
        ),
    ]
