# Generated by Django 5.1.4 on 2025-11-06 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2bmanagement', '0041_district'),
        ('claim', '0055_remove_claiminformation_ancillary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claiminformation',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claim_distrcit', to='b2bmanagement.district'),
        ),
        migrations.AddField(
            model_name='claiminformation',
            name='issued_police_station',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
