# Generated by Django 5.1.4 on 2025-11-06 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2bmanagement', '0041_district'),
        ('claim', '0056_claiminformation_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claiminformation',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claim_district', to='b2bmanagement.district'),
        ),
    ]
