# Generated by Django 5.1.4 on 2025-11-06 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0057_alter_claiminformation_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='effective_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
