# Generated by Django 5.1.4 on 2025-11-07 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0058_currency_effective_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='claiminformation',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='claim.currency'),
        ),
    ]
