# Generated by Django 5.1.4 on 2025-11-07 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0059_claiminformation_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='claiminformation',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='claiminformation',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
