# Generated by Django 5.1.4 on 2025-11-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0060_claiminformation_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claiminformation',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
