# Generated by Django 5.1.4 on 2025-11-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0061_claiminformation_exchange_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimcostitem',
            name='currency_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='claiminformation',
            name='file_status',
            field=models.PositiveBigIntegerField(choices=[(0, 'DECLINED'), (1, 'APPROVED'), (2, 'SUBMITTED'), (3, 'SETTELED'), (4, 'PENDING'), (5, 'PROCESSING'), (6, 'RETURN'), (7, 'DOCUMENT-WANTED'), (8, 'INITIATED')], default=4),
        ),
    ]
