# Generated by Django 5.1.4 on 2025-11-16 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0062_claimcostitem_currency_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claiminformation',
            name='is_edited_claim_supervisor',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
