# Generated by Django 5.1.4 on 2025-11-16 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0063_claiminformation_is_edited_claim_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimcostitem',
            name='claim_supervisor_deduction',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='claimcostitem',
            name='claim_supervisor_settled',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
