# Generated by Django 5.1.4 on 2025-11-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0064_claimcostitem_claim_supervisor_deduction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimcostitem',
            name='key',
            field=models.CharField(blank=True, choices=[('icu_or_ccu_or_nsu', 'ICU/CCU/NSU'), ('consultation_fee', 'Consultation fee'), ('medical_investigation', 'Medical Investigation'), ('investigation_fee', 'Investigation Fee'), ('ancillary', 'Ancillary'), ('medicine', 'Medicine'), ('other', 'Other'), ('others', 'others'), ('package_cost', 'Package Cost'), ('room_rent1', 'Room Rent1'), ('room_rent', 'Room Rent'), ('day_care_amount', 'Day Care Amount'), ('emergency_treatment', 'Emergency Treatment'), ('physiotherapy_fee', 'Physiotherapy Fee'), ('outstanding_medical_bills', 'Outstanding Medical Bills'), ('funeral_expenses', 'Funeral Expenses'), ('surgery', 'Surgery')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='claiminformation',
            name='claim_type',
            field=models.PositiveBigIntegerField(choices=[(0, 'DECLINED'), (1, 'APPROVED'), (2, 'SUBMITTED'), (3, 'SETTELED'), (4, 'PENDING'), (5, 'PROCESSING'), (6, 'RETURN'), (7, 'DOCUMENT-WANTED'), (8, 'INITIATED')], default=4),
        ),
    ]
