# Generated by Django 5.1.4 on 2025-11-18 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0065_alter_claimcostitem_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claiminformation',
            name='claim_type',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name=[(1, 'Meternity NVD/Normal delivery'), (2, 'Maternity LUCS Cesarean'), (3, 'Maternity Legal abortion')]),
        ),
    ]
