# Generated by Django 5.1.4 on 2025-11-19 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0066_alter_claiminformation_claim_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claiminformation',
            name='death_of_departure',
            field=models.DateField(blank=True, null=True),
        ),
    ]
