# Generated by Django 5.1.4 on 2025-11-19 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0067_alter_claiminformation_death_of_departure'),
    ]

    operations = [
        migrations.AddField(
            model_name='claiminformation',
            name='fir_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
