# Generated by Django 5.1.4 on 2025-11-19 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0068_claiminformation_fir_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='claiminformation',
            name='diagnosis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
