# Generated by Django 5.1.4 on 2025-11-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0069_claiminformation_diagnosis'),
    ]

    operations = [
        migrations.AddField(
            model_name='claiminformation',
            name='incident_type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
