# Generated by Django 5.1.4 on 2025-11-26 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0070_claiminformation_incident_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='claiminformation',
            name='discount_perchantage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
