# Generated by Django 5.1.4 on 2025-11-29 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0071_claiminformation_discount_perchantage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claiminformation',
            name='file_status',
            field=models.PositiveBigIntegerField(choices=[(0, 'DECLINED'), (1, 'APPROVED'), (2, 'SUBMITTED'), (3, 'SETTELED'), (4, 'Under Processing'), (5, 'PROCESSING'), (6, 'RETURN'), (7, 'DOCUMENT-WANTED'), (8, 'INITIATED')], default=4),
        ),
    ]
