# Generated by Django 5.1.4 on 2025-12-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0072_alter_claiminformation_file_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimcostitem',
            name='remarks_claim_supervisor',
            field=models.TextField(blank=True, null=True),
        ),
    ]
