# Generated by Django 5.1.4 on 2026-01-27 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0073_claimcostitem_remarks_claim_supervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filetransferhistory',
            name='status',
            field=models.PositiveBigIntegerField(choices=[(0, 'DECLINED'), (1, 'APPROVED'), (2, 'SUBMITTED'), (3, 'SETTELED'), (4, 'PENDING'), (5, 'PROCESSING'), (6, 'RETURN'), (7, 'DOCUMENT-WANTED'), (8, 'INITIATED')], default=4),
        ),
        migrations.AlterField(
            model_name='filetransferhistory',
            name='status_after',
            field=models.PositiveBigIntegerField(choices=[(0, 'DECLINED'), (1, 'APPROVED'), (2, 'SUBMITTED'), (3, 'SETTELED'), (4, 'PENDING'), (5, 'PROCESSING'), (6, 'RETURN'), (7, 'DOCUMENT-WANTED'), (8, 'INITIATED')], default=4),
        ),
        migrations.AlterField(
            model_name='filetransferhistory',
            name='status_before',
            field=models.PositiveBigIntegerField(choices=[(0, 'DECLINED'), (1, 'APPROVED'), (2, 'SUBMITTED'), (3, 'SETTELED'), (4, 'PENDING'), (5, 'PROCESSING'), (6, 'RETURN'), (7, 'DOCUMENT-WANTED'), (8, 'INITIATED')], default=4),
        ),
    ]
