# Generated by Django 5.1.4 on 2025-06-23 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_familymember_department_designation_employeegroup_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='department',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='designation',
            name='department',
        ),
        migrations.RemoveField(
            model_name='designation',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='designation',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='employeesfamily',
            name='employee_designation',
        ),
        migrations.RemoveField(
            model_name='employeegroup',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='employeegroup',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='employeesfamily',
            name='policy_holder',
        ),
        migrations.RemoveField(
            model_name='employeesfamily',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='employeesfamily',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='FamilyMember',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Designation',
        ),
        migrations.DeleteModel(
            name='EmployeeGroup',
        ),
        migrations.DeleteModel(
            name='EmployeesFamily',
        ),
    ]
