# Generated by Django 5.1.4 on 2025-08-14 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_department_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='system_genarate',
            field=models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], default='N', max_length=5),
        ),
    ]
