# Generated by Django 5.1.4 on 2025-08-14 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_system_genarate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='system_genarate',
            new_name='system_generate',
        ),
    ]
