# Generated by Django 5.1.4 on 2025-10-18 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_emailconfiguration_emailtemplate'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='emailtemplate',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='group',
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='user',
        ),
    ]
