# Generated by Django 5.1.4 on 2025-10-18 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_emailtemplate_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='status',
            field=models.PositiveBigIntegerField(choices=[(0, 'DECLINED'), (1, 'APPROVED'), (2, 'SUBMITTED'), (3, 'SETTELED'), (4, 'PENDING'), (5, 'PROCESSING'), (6, 'RETURN'), (7, 'DOCUMENT-WANTED')], default=1),
        ),
    ]
