# Generated by Django 5.1.4 on 2025-08-17 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b2bproduct', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='contact_number',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='address',
        ),
        migrations.RemoveField(
            model_name='product',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='email',
        ),
        migrations.RemoveField(
            model_name='product',
            name='nid_number',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='upload_nid',
        ),
    ]
