# Generated by Django 5.1.4 on 2025-08-17 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b2bproduct', '0003_policy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policy',
            old_name='claim',
            new_name='product',
        ),
    ]
