from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path,include
from .views import (create_management_orgonization,create_insure,b2bOrganizationList,assignPolicies,addAssignPolicies,b2bSetting,addOrganizationType,b2bCustomerEdit,bankView,organizationsBoard,updateOrganization,
                    OrganizationView,
                    hospitalPaginationList,
                    hospitalList,
                    OrganizationPolicyView,
                    create_hospital,
                    BankView,
                    getOrganizationData,
                    getBankList,
                    BankViewSigleList,
                    DesignationView,
                    designiationPaginationList,
                    DesignationViewSigleList,
                    designationView,
                    SalaryRangeView,
                    salaryRangePaginationList,
                    salaryRangeView,
                    SalaryRangeViewSigleList,
                    PlanView,
                    planPaginationList,
                    planView,
                    PlanViewSigleList,
                    InsurerView,
                    insurerView,
                    insurerPaginationList,
                    InsurerViewSigleList,
                    InsurerPolicyCreate,
                    OrganizationPolicyCreate,
                    CompanyPlanView,
                    CompanyPlanCreate,
                    CompanyPlanPaginationList,
                    CompanyPlanListView,
                    CompanyDetailAPIView,
                    InsurerDetailsView,
                    OrganizationDetailsView,
                    companyTypeView,
                    companyPaginationList,
                    CompanyTypeView,
                    CompanyTypeViewSigleList,
                    DistrictView,
                    districtView,
                    DistrictiewPaginationSigleList,
                    DistrictiewSigleList,
                    HopitalCreateAPIView,
                    CreateGop,
                    GopsView,
                    GOPCreateAPIView,
                    gopPaginationList
                    )

from rest_framework.routers import DefaultRouter
router = DefaultRouter()

# router.register('devices',CampaignViewSet,basename='devices')
urlpatterns = [
    path('add-new-b2b-orgonization/',create_management_orgonization,name='add-new-b2b-orgonization'),
    path('add-new-insure/',create_insure,name='add-new-insure'),
    path('hospitals/',hospitalList,name='hospitals'),
    path('hospital-save/',HopitalCreateAPIView.as_view(),name='hospital-save'),
    path('hospital-save/<int:pk>/', HopitalCreateAPIView.as_view(), name='hospital-save'),
    path('hospital-list/',hospitalPaginationList,name='hospital-list'),
    path('add-new-hospital/',create_hospital,name='add-new-hospital'),
    path('b2b-organization-list/',b2bOrganizationList,name='b2b-organization-list'),
    path('assign-policies/',assignPolicies,name='assign-policies'),
    path('add-assign-policies/',addAssignPolicies,name='add-assign-policies'),
    path('b2b-setting/',b2bSetting,name='organization-types'),
    path('add-organization-type/',addOrganizationType,name='add-organization-type'),
    path('b2b-customer-edit/',b2bCustomerEdit,name='b2b-customer-edit'),
    #Bank Information URL
    path('bank/',bankView,name='bank'),
    path('bank-list/',getBankList,name='bank-list'),
    path('bank-save/',BankView.as_view(),name='bank-save'),
    path('bank-save/<int:pk>/',BankView.as_view(),name='bank-save'),
    path('bank-details/<int:item_id>/',BankViewSigleList.as_view(),name='bank-details'),
    #Designation Information URL
    path('designation-view/',designationView,name='designation-view'),
    path('designation-list/',designiationPaginationList,name='designation-list'),
    path('designation-save/',DesignationView.as_view(),name='designation-save'),
    path('designation-save/<int:pk>/',DesignationView.as_view(),name='designation-save'),
    path('designation-details/<int:item_id>/',DesignationViewSigleList.as_view(),name='designation-details'),
    # Create Plan  URL
    path('plan-view/',planView,name='plan-view'),
    path('plans/',planPaginationList,name='plans'),
    path('create-plan/',PlanView.as_view(),name='create-plan'),
    path('create-plan/<int:pk>/',PlanView.as_view(),name='create-plan'),
    path('plan-details/<int:item_id>/',PlanViewSigleList.as_view(),name='plan-details'),
   
        
     # Create Insurer  URL
    path('insurer-view/',insurerView,name='insurer-view'),
    path('insurer-list/',insurerPaginationList,name='insurer-list'),
    path('create-insurer/',InsurerView.as_view(),name='create-insurer'),
    path('create-insurer-policy/',InsurerPolicyCreate.as_view(),name='create-insurer-policy'),
    path('create-insurer/<int:pk>/',InsurerView.as_view(),name='create-insurer'),
    path('insurer-details/<int:item_id>/',InsurerViewSigleList.as_view(),name='insurer-details'),    
    path('insurer-view-details/<int:pk>/',InsurerDetailsView.as_view(),name='insurer-view-details'),    
        
    path('salary-range-view/',salaryRangeView,name='salary-range-view'),
    path('salary-range-list/',salaryRangePaginationList,name='salary-range-list'),
    path('salary-range-save/',SalaryRangeView.as_view(),name='salary-range-save'),
    path('salary-range-save/<int:pk>/',SalaryRangeView.as_view(),name='salary-range-save'),
    path('salary-range-details/<int:item_id>/',SalaryRangeViewSigleList.as_view(),name='salaryrange-details'),    
        
    path('organizations-board/',organizationsBoard,name='organizations-board'),
    path('organizations/',getOrganizationData,name='organizations'),
    path('create-new-organization/',OrganizationView.as_view(),name='create-new-organization'),
    path('create-organization-policy/',OrganizationPolicyCreate.as_view(),name='create-organization-policy'),
    path('add-b2b-organization/<int:pk>/',OrganizationView.as_view(),name='add-b2b-organization'),
    path('update-b2b-organization/<int:id>', updateOrganization, name='edit-b2b-organization'),
    path('company-wise-plan/',CompanyPlanView,name='company-wise-plan'),
    path('company-plan-create/',CompanyPlanCreate.as_view(),name='company-plan-create'),
    path('company-plan-list/',CompanyPlanPaginationList,name='company-plan-list'),
    path('company-plans/',CompanyPlanListView,name='company-plans'),
    path('company-plan-details/<int:pk>/',CompanyDetailAPIView.as_view(),name='company-plan-details'),  
    path('organization-view-details/<int:pk>/',OrganizationDetailsView.as_view(),name='organization-view-details'),    
    path('organization-policy-delete/',OrganizationPolicyView.as_view(),name='organization-policy-delete'),    

       # Create Company Type  URL
    path('company-type-view/',companyTypeView,name='company-type-view'),
    path('company-type-list/',companyPaginationList,name='company-type-list'),
    path('create-company-type/',CompanyTypeView.as_view(),name='create-company-type'),
    path('create-company-type/<int:pk>/',CompanyTypeView.as_view(),name='create-company-type'),
    path('company-type-details/<int:item_id>/',CompanyTypeViewSigleList.as_view(),name='company-type-details'),   
   
    path('district/',districtView,name='district'),
    path('district-list/',DistrictiewPaginationSigleList,name='district-list'),
    path('create-district/',DistrictView.as_view(),name='create-district'),
    path('create-district/<int:pk>/',DistrictView.as_view(),name='create-district'),
    path('district-details/<int:item_id>/',DistrictiewSigleList.as_view(),name='district-details'),  
    path('create-gop/',CreateGop,name='create-gop'),
    path('gop/',GOPCreateAPIView.as_view(),name='gop'),
    path('gops/',GopsView,name='gops'),
    path('gop-list/',gopPaginationList,name='gop-list'),
]